services:
    zookeeper:
        image: *zookeeper-image
        instances:
            zookeeper-1:
                <<: *zookeeper
                ship: *ship-1
    gns-reinit:
        image: *gns-image
        requires:
            - zookeeper
        instances:
            gns-reinit:
                <<: *gns-reinit
                ship: *ship-1
