name: gns

default_env: &default-env
  CONFIG: /root/gns.d/gns.yaml
  RULES_DIR: /root/rules
  REPO_DIR: /root/rules.git
  REPO_URL: https://github.yandex-team.ru/monitoring/gns-rules
  ELASTICSEARCH_URL: http://elasticlog.yandex.net:9200
  SMS_URL: https://golem.yandex-team.ru/api/sms/send.sbml
  EMAIL_FROM: gns@gns

volumes: &volumes
  /root/rules.git: /tmp/gns-rules.git
  /root/rules: /tmp/gns-rules

ships:
  local:
    ip: &ship 172.17.42.1

gns-image: &gns-image nikicat/gns-ut

services:
  zookeeper:
    image: nikicat/zookeeper-ut
    instances:
      zk:
        ship: local
        ports: {client: 2181, peer: 2888, leader_election: 3888}
        volumes:
          /var/lib/zookeeper: /data/zookeeper
  exim:
    image: nikicat/exim-ut
    instances:
      exim: &exim
        ship: local
        ports: {smtp: 25}
  gns-fetcher:
    image: *gns-image
    requires:
      - zookeeper
    instances:
      gns-fetcher:
        ship: local
        env:
          <<: *default-env
          MODULE: fetcher
        volumes: *volumes
  gns-api:
    image: *gns-image
    requires:
      - zookeeper
    instances:
      gns-api:
        ship: local
        ports: {http: 7887}
        env:
          <<: *default-env
          MODULE: api
  gns-splitter:
    image: *gns-image
    requires:
      - zookeeper
    instances:
      gns-splitter:
        ship: local
        env:
          <<: *default-env
          MODULE: splitter
        volumes: *volumes
  gns-worker:
    image: *gns-image
    requires:
      - zookeeper
      - exim
    instances:
      gns-worker:
        ship: local
        env:
          <<: *default-env
          MODULE: worker
          SMTP_HOST: *ship
        volumes: *volumes
  gns-collector:
    image: *gns-image
    requires:
      - zookeeper
    instances:
      gns-collector:
        ship: local
        env:
          <<: *default-env
          MODULE: collector

#registries:
#  docker-3:
#    registry: http://docker-3.i.fog.yandex.net:5000/v1/
#    email: nbryskin@yandex-team.ru
