name: gns

default_env: &default-env
  CONFIG: /root/gns.d/gns.yaml
  RULES_DIR: /root/rules
  REPO_DIR: /root/rules.git
  REPO_URL: https://github.yandex-team.ru/monitoring/gns-rules
  ELASTICSEARCH_URL: !!python/object/apply:os.getenv [ELASTICSEARCH_URL, "http://elasticlog.yandex.net:9200"]
  YA_SMS_URL: !!python/object/apply:os.getenv [YA_SMS_URL, "https://golem.yandex-team.ru/api/sms/send.sbml"]
  EMAIL_FROM: !!python/object/apply:os.getenv [EMAIL_FROM, "gns@gns"]

volumes: &volumes
  /root/rules.git: /tmp/gns-rules.git
  /root/rules: /tmp/gns-rules

gns-image: &gns-image !!python/object/apply:os.getenv [DOCKER_GNS_IMAGE, nikicat/gns-ut]
zookeeper-image: &zookeeper-image !!python/object/apply:os.getenv [DOCKER_ZOOKEEPER_IMAGE, nikicat/zookeeper]

ships:
  ship:
    ip: !!python/object/apply:os.getenv [SHIP_1, 172.17.42.1]

services:
  zookeeper:
    image: *zookeeper-image
    instances:
      zk-1:
        ship: ship
        ports: {client: 2181, peer: 2888, leader_election: 3888}
        volumes:
          /var/lib/zookeeper: /data/zookeeper
  gns-reinit:
    image: nikicat/gns-ut
    requires:
      - zookeeper
    instances:
      gns-reinit:
        ship: ship
        env:
          <<: *default-env
          MODULE: reinit
