language: c
env:
    - PYTHONPATH=/usr/lib/pypy3/site-packages
before_install:
    - sudo apt-add-repository 'deb http://nikicat.github.io/pypy3-repo ./'
    - sudo apt-add-repository ppa:yandex-sysmon/zookeeper-3.4 -y
    - sudo apt-get update
    - sudo apt-get install zookeeperd pypy3 -y --force-yes
    - sudo ln -fs pypy3 /usr/bin/python
    - sudo mkdir /usr/lib/pypy3/site-packages
    - curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | sudo PYTHONPATH=/usr/lib/pypy3/site-packages pypy3
    - sudo ln -fs /usr/lib/pypy3/bin/easy_install /usr/local/bin/easy_install
    - sudo /usr/share/zookeeper/bin/zkServer.sh start
install:
    - sudo PYTHONPATH=/usr/lib/pypy3/site-packages easy_install tox coveralls
script:
    - /usr/lib/pypy3/bin/tox -v
after_success:
    - /usr/lib/pypy3/bin/coveralls
before_deploy:
    - git checkout master
    - git config user.email "travisbot@travis-ci.org"
    - git config user.name "Travis-CI Bot"
    - (git log -1 --pretty=%B | grep 'Merge pull request') && bumpversion --verbose minor || true
    - git remote remove origin
    - git remote add origin git@github.com:yandex-sysmon/gns
    - openssl rsa -in .deploy.pem -passin env:DEPLOYKEYPASS >> ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - git push origin master
    - git push --tags --force
deploy:
    provider: pypi
    user: nikicat
    password:
        secure: i9zNWTqaqWjKp4hHVXA0wWvCFS5ic7ne3nc6WP7fanQLC5y1/tQxsnmMVN02aThfpNoCZKh82rWjs/wXXxUq5Q4egXFaOjMPoyIsb8EGHFi4y1FMW/wSnw/iBXFYruWf/k+JQz2t+dj1/EpHj4sLGMPRjANdK2+fwrDFNIlUIBs=
    distributions: sdist
    on:
        repo: yandex-sysmon/gns
notifications:
    hipchat:
        rooms:
            secure: pR1BULcnp7Zw+bsCe0bn6ajulhSPdGFg2rYt3pxCxygOmq1QE/iDV6awryqdk6nIGFTXjCjUTd1bI3KXqGKdGIcYeQ78mP+NG9sMm2anZ5ZKjbInHslg6yglTdjDZ7Q0iWDoiGUMbiAQwo0mY7aiWp8Zbo0VdQbTckmaL+upIh4=
