language: python
python:
    - pypy3
before_install:
    - sudo apt-add-repository ppa:yandex-sysmon/zookeeper-3.4 -y
    - sudo apt-get update
    - sudo apt-get install zookeeperd -y --force-yes
    - sudo /usr/share/zookeeper/bin/zkServer.sh start
install:
    - pip install tox coveralls
script:
    - tox -v
after_success:
    - coveralls
notifications:
    hipchat:
        rooms:
            secure: pR1BULcnp7Zw+bsCe0bn6ajulhSPdGFg2rYt3pxCxygOmq1QE/iDV6awryqdk6nIGFTXjCjUTd1bI3KXqGKdGIcYeQ78mP+NG9sMm2anZ5ZKjbInHslg6yglTdjDZ7Q0iWDoiGUMbiAQwo0mY7aiWp8Zbo0VdQbTckmaL+upIh4=
