language: c
env:
  - "PYTHONPATH=/usr/lib/pypy3/site-packages"
before_install:
  - sudo apt-add-repository 'deb http://nikicat.github.io/pypy3-repo ./'
  - sudo apt-add-repository ppa:yandex-sysmon/zookeeper-3.4 -y
  - sudo apt-get update
  - sudo apt-get install zookeeperd pypy3 -y --force-yes
  - sudo ln -s pypy3 /usr/bin/python
  - sudo mkdir /usr/lib/pypy3/site-packages
  - curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | sudo pypy3
  - sudo /usr/share/zookeeper/bin/zkServer.sh start
install:
  - sudo easy_install-3.2 .
before_script:
  - sudo easy_install-3.2 `cat test_requirements.txt`
script:
  - py.test run-tests.py -v --cov gns --cov-report term-missing #--pep8 gns
after_success:
  - coveralls
