name: gns

default_env: &default-env
  CONFIG: /root/gns.d/gns.yaml
  RULES_DIR: /root/rules
  REPO_DIR: /root/rules.git

volumes: &volumes
  /root/rules.git: /tmp/gns-rules.git
  /root/rules: /tmp/gns-rules

services:
  zookeeper:
    image: quay.io/nikicat/zookeeper
    instances:
      zk:
        ship: local
        ports: {client: 2181, peer: 2888, leader_election: 3888}
        volumes:
          /var/lib/zookeeper: /data/zookeeper
  gns-fetcher:
    image: nikicat/gns-untrusted
    requires:
      - zookeeper
    instances:
      gns-fetcher:
        ship: local
        env:
          <<: *default-env
          MODULE: fetcher
        volumes: *volumes
  gns-api:
    image: nikicat/gns-untrusted
    requires:
      - zookeeper
    instances:
      gns-api:
        ship: local
        ports: {http: 7887}
        env:
          <<: *default-env
          MODULE: api
  gns-splitter:
    image: nikicat/gns-untrusted
    requires:
      - zookeeper
    instances:
      gns-splitter:
        ship: local
        env:
          <<: *default-env
          MODULE: splitter
        volumes: *volumes
  gns-worker:
    image: nikicat/gns-untrusted
    requires:
      - zookeeper
    instances:
      gns-worker:
        ship: local
        env:
          <<: *default-env
          MODULE: worker
        volumes: *volumes
  gns-collector:
    image: nikicat/gns-untrusted
    requires:
      - zookeeper
    instances:
      gns-collector:
        ship: local
        env:
          <<: *default-env
          MODULE: collector

#registries:
#  docker-3:
#    registry: http://docker-3.i.fog.yandex.net:5000/v1/
#    email: nbryskin@yandex-team.ru

ships:
  local:
    ip: 172.17.42.1
