# See for details:
#   http://docs.python.org/3.2/library/logging.config.html#dictionary-schema-details

disable_existing_loggers: false
formatters:
    standard:
        format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
    console:
        level: DEBUG
        class: logging.StreamHandler
        formatter: standard
    file:
        level: DEBUG
        class: logging.FileHandler
        filename: test.log
        mode: w+
        formatter: standard

root:
    level: DEBUG
    handlers:
        - console
        - file

loggers:
    raava:
        level: DEBUG
    raava.worker:
        level: INFO
    cherrypy:
        level: DEBUG
        handlers:
            - console
            - file
    kazoo.client:
        level: WARNING

